name: CI
on: [push]
jobs:
  lint:
    name: Lint and Format
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install modules
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Run Prettier
      uses: creyD/prettier_action@v4.3