name: CI
on: [push]
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install modules
      run: npm ci

    - name: Run ESLint
      run: npm run lint